### PR TITLE
Fix TypeScript optional Props

### PR DESCRIPTION
**Pull request by lnmunhoz**
Fix for correct optional properties syntax. Otherwise it will require all the props to be passed in the component.

### CODE REVIEW

**Comment by samuelmeuli** [comment]
Thanks for the PR!

Are you sure this is an issue? I think props with corresponding `defaultProps` are already optional, see [the TypeScript docs](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#support-for-defaultprops-in-jsx).

**Comment by lnmunhoz** [comment]
It's an issue if you are using typescript because if you don't use optional properties in the interface it will assume it is **required** so the compiler will not be happy about that.

Have you tried to use in a tsx file without passing the required params? You will get this error:

image

**Comment by samuelmeuli** [comment]
Just tested this in a new `create-react-app` project and I'm not encountering any issues.

If I omit the required `apiKey` prop, the compiler complains:

```
Failed to compile.

/path/to/App.tsx
TypeScript error in /path/to/App.tsx(8,5):
Property 'apiKey' is missing in type '{}' but required in type 'Pick<Readonly<Props> & Readonly<{ children?: ReactNode; }>, "apiKey" | "children">'.  TS2741
```

If I omit any of the optional props, everything works fine and there are no compiler warnings.

Are you using an old version of TypeScript?

**Comment by lnmunhoz** [comment]
Interesting, we are using the latest TypesScript version `3.8.3` and it claims that this props are needed. But I did some tests in a empty codesandbox and you're right. Internally the props and defaultProps are merged as it says [here](https://www.bookstack.cn/read/typescriptlang-3.7/spilt.58.055dccf6c3f8aae3.md) so it shouldn't be a problem.

I was trying to find if we have some weird tsconfig, and updated @types/react as well but no success to figure out what is wrong.

Anyways, the problem is definitely in our side so I will close this PR. 
Thank you for your time!

**Comment by VictorPietro** [comment]
Hi @lnmunhoz, did you find any solution to this? Even though it's not specifically an error, I'm also having Typescript accusing error for optional parameters.

**Pull request closed without merging**
